name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - uses: jirutka/setup-alpine@v1
        with:
          arch: x86
          packages: >
            cargo

      - name: Run the tests
        run: cargo test -- --nocapture
        shell: alpine.sh {0}
